config-sparse:
  modules:
    rebalancer:
      config:
        balance_config_file_selector:
          contents:
            suggested-value: ucp/plugins/Ascension-AI-Balance-*/resources/balance/ascension_ai.json
  plugins: {}
meta:
  version: 1.0.0
